[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "py-dss-toolkit"
version = "0.17.0"
description = "Advanced Python Tools for OpenDSS Powered by EPRI."
readme = "README.md"
license = "MIT"
authors = [
  {name = "Paulo Radatz", email = "paulo.radatz@gmail.com"}
]
requires-python = ">=3.10"
keywords = ["OpenDSS", "Python", "Power Systems", "Distribution Systems", "Energy"]
dependencies = [
	"py-dss-interface>=2.3.0",
	"pandas>=2.2",
	"matplotlib>=3.10",
	"plotly>=5.20",
	"networkx>=3.0",
	"tqdm>=4.66"
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Science/Research",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Scientific/Engineering",
  "Topic :: Software Development :: Libraries :: Python Modules"
]

[project.optional-dependencies]
dev = [
	"pyarrow",
]

[project.urls]
"Changelog" = "https://github.com/PauloRadatz/py_dss_toolkit/blob/master/CHANGELOG.rst"
"Issue Tracker" = "https://github.com/PauloRadatz/py_dss_toolkit/issues"
"Source" = "https://github.com/PauloRadatz/py_dss_toolkit"

[tool.setuptools]
packages = { find = {where = ["src"]} }

[tool.pytest.ini_options]
norecursedirs = ["migrations"]
python_files = ["test_*.py", "*_test.py", "tests.py"]
addopts = [
    "-ra",
    "--strict-markers",
    "--doctest-modules",
    "--doctest-glob=\\*.rst",
    "--tb=short"
]
testpaths = ["tests"]

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["py_dss_toolkit", "tests"]
parallel = true

[tool.coverage.report]
show_missing = true
precision = 2
omit = ["*migrations*"]

[tool.ruff]
line-length = 120
src = ["src", "tests"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E203"]

[tool.ruff.lint.isort]
known-first-party = ["py_dss_toolkit"]
force-single-line = true

